#!/bin/bash

# Telegram bot token and chat ID
TELEGRAM_BOT_TOKEN="6751722536:AAHN6KBCoLvXke15WofciV9sYbIPQKBEQ6Q"
TELEGRAM_CHAT_ID="-1002009081836"

# MongoDB connection details
MONGO_HOST="localhost"
MONGO_PORT="27017"
MONGO_DATABASE="test"
MONGO_USERNAME="admin"
MONGO_PASSWORD="admin@123"

# Backup directory
BACKUP_DIR="/home/backup/"

# Date format for backup file
DATE_FORMAT=$(date +"%Y%m%d%H%M%S")

# Create backup directory if not exists
mkdir -p "$BACKUP_DIR"

# Run mongodump to perform the backup
mongodump --host "$MONGO_HOST" --port "$MONGO_PORT" --username "$MONGO_USERNAME" --password "$MONGO_PASSWORD" --authenticationDatabase admin --db "$MONGO>

# Check if the backup was successful
if [ $? -eq 0 ]; then
  echo "  MongoDB backup completed successfully."

  # Get the name of the created folder
  FOLDER_NAME="intrana_$DATE_FORMAT"

  # Create a compressed archive of the folder
  tar -czvf "$BACKUP_DIR/$FOLDER_NAME.tar.gz" -C "$BACKUP_DIR" "$FOLDER_NAME"

  # Send the entire backup folder to Telegram group
  curl -s -X POST "https://api.telegram.org/bot$TELEGRAM_BOT_TOKEN/sendDocument" -F "chat_id=$TELEGRAM_CHAT_ID" -F "document=@$BACKUP_DIR/$FOLDER_NAME.ta>
else
  echo "Error:   MongoDB backup failed."
fi

